### PR TITLE
Added star-icon

### LINKED ISSUE #124: UI : Mark dashboards as favorite.
# Description 
Implement the ability for users to mark dashboards as favorites. Introduce a "star" icon or similar UI element next to each dashboard, allowing users to easily mark and access their favorite dashboards.

### PR DESCRIPTION
**Pull request by PratikshaPatil77**
# Description
Added star icon to implement the ability for users to mark dashboards as favorites.

Fixes #124 

# Testing
It is clickable star icon initially it will be hollow or outline star when user click the star icon will become solid star to show dashboard as favorite.

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ x ] I have self-reviewed this PR.
- [ x ] I have removed all print-debugging and commented-out code that should not be merged.
- [ x ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Comment by sunitakawane** [comment]
I see the code for option in dropdown but I do not see it in the UI. Can you paste the screenshot in the PR comment.

**Comment by sonamgupta21** [comment]
Please use these SVG icons for the outlined and filled star. Also, define the corresponding CSS in `dashboard.css`
star-outline
start-filled

**Comment by nbhavana** [comment]
@sunitakawane I don't think  the star icon should be in dropdown, it should saved dashboard page next to view, delete, duplicate icons.
image

**Comment by PratikshaPatil77** [comment]
In output I am not able to see the changes which I was made in PR
Screenshot 2023-12-12 at 3 38 28 PM

**Comment by PratikshaPatil77** [comment]
Please help me .

**Comment by PratikshaPatil77** [comment]
Hi, @sonamgupta21 @sunitakawane 
I've made the changes and it is ready to review.
Thank you.

**Comment by sunitakawane** [comment]
for small screen , the star icon is not completely visible.  Can you take a look. 
Screenshot 2023-12-15 at 1 56 18 PM

**Comment by PratikshaPatil77** [comment]
Ok let me check.

**Comment by sunitakawane** [comment]
@sonamgupta21 can you verify this

**Comment by sonamgupta21** [comment]
> @sonamgupta21 can you verify this

looks good to me.

**Review by nbhavana — APPROVED** [review]
lgtm. Only one thing I would like to mention is that we should only see code changes. Currently, I see so many indentation changes. Please make sure that the next PR should not have indentation changes, unless it is required.

**Pull request merged**
