### PR TITLE
title has been changed

### PR DESCRIPTION
**Pull request by KalePallavi**
Static folder in dashboard.html file 
title changed

### CODE REVIEW

**Comment by KalePallavi** [comment]
static folder in feedback.html file changes

**Comment by sunitakawane** [comment]
Can you put a link for the issue you are working on?

**Comment by KalePallavi** [comment]
> Can you put a link for the issue you are working on?

yes

**Comment by KalePallavi** [comment]
> > Can you put a link for the issue you are working on?
> 
> yes
https://github.com/siglens/siglens/pull/69

**Comment by KalePallavi** [comment]
yes
https://github.com/KalePallavi/siglens/commit/a4b4b711586832e751fbfab8742716eda0bdde2b

**Pull request closed without merging**
