### PR TITLE
add copy icon in Dashboard Settings Page

### LINKED ISSUE #126: Add "Copy" Icon for JSON Config in Dashboard Settings Page
# Description
Include a "Copy" icon for users to easily copy the JSON.

### PR DESCRIPTION
**Pull request by kashmii**
# Description
- added a copy icon for both light and dark mode
- hovering over the 'Copy' icon show a 'Copy' tooltip
- When the user clicks, and the JSON gets copied, the tooltip should display 'Copied!'

Fixes #126  (link all the GitHub issues this addresses)

### remarks
- about css, I diverted the code from '.dropdown-style .copy' part in the same file

---

https://github.com/siglens/siglens/assets/75294723/c4901362-4fb6-48b7-b8ad-3f1c17c5c384

# Testing
Describe how you tested this code. How can the reviewers reproduce your tests?

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Comment by kashmii** [comment]
could you check this? thanks!


https://github.com/siglens/siglens/assets/75294723/5827b95f-159b-4da3-b1d7-9c346697df7d

**Comment by sonamgupta21** [comment]
Hey @kashmii,
I've identified an issue. After switching from "Copied" to "Copy," the tooltip reappears without any hover and doesn't close when clicking outside.

https://github.com/siglens/siglens/assets/71771131/c532de55-926a-4f42-909b-d5fdffe0f3be

**Comment by kashmii** [comment]
Hi, I changed this like you showed.
Is this OK? Thank you.


https://github.com/siglens/siglens/assets/75294723/70b83eb6-f342-4884-8b07-cb2c81e992b8

**Comment by sonamgupta21** [comment]
Hi @kashmii,
The bug is still present.
To clarify: the issue is that the tooltip reappears without any hover, then it changes from 'copied' to 'copy,' and it does not even close when I click outside anywhere.

Let me know if you have any questions.

**Comment by kashmii** [comment]
> I've identified an issue. After switching from "Copied" to "Copy," the tooltip reappears without any hover and doesn't close when clicking outside.

I misunderstood this comment and didn't notice that behavior. Sorry for bothering you.

I think I fixed it (I hope so), could you have a look?
Thank you for your patience.

https://github.com/siglens/siglens/assets/75294723/b7fd42e5-8294-4c1f-b4b6-8eecec1cc812

**Review by sonamgupta21 — APPROVED** [review]
This looks good now. Thanks for your contribution.

**Pull request merged**
