### PR TITLE
Visualization tab update fix

### LINKED ISSUE #646: [BUG] Visualization tab doesn't update
# Description
When you run a query that produces a visualization and then go to the visualization tab and then run a different query, you see the visualization you were already seeing.

# Steps to Reproduce
1. Ingest some test data
2. Run this query on the UI: `* | timechart avg(latency) by http_method span=1h`
3. Beneath the query, there's two tabs: Table, and Visualization. Select the Visualization tab and you should see a bar graph with 6 bars.
4. Stay on Visualization and run `* | timechart avg(latency) span=1h`

Notice that the bar graph remains unchanged, but is incorrect. If you go to the Table tab and then back to Visualization, you'll see the correct graph, which has just one bar. Also you can run it with a query that doesn't have a visualization, like `* | http_status=20*`. If you're on the Visualization tab already, it doesn't get updated. But once you go to Table and then back to Visualization, you correctly see the message "This query does not contain visualization data"

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: 557458f

# (Optional) Additional Context
Add anything else we should know about this problem.

### PR DESCRIPTION
**Pull request by sharma2910**
# Description
Added code to reset chart on query update.

Screenshot 2024-03-26 at 11 43 49 AM
Screenshot 2024-03-26 at 11 45 54 AM

Fixes #646

# Testing

1. Ingest some test data
2. Run this query on the UI: * | timechart avg(latency) by http_method span=1h
3. Beneath the query, there's two tabs: Table, and Visualization. Select the Visualization tab and you should see a bar graph with 6 bars.
4. Stay on Visualization and run * | timechart avg(latency) span=1h
5. The chart data should update on query change

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ ] I have self-reviewed this PR.
- [ ] I have removed all print-debugging and commented-out code that should not be merged.
- [ ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by nbhavana — COMMENTED** [review]
This change does not seem to fix the issue. I followed the steps given in the issue and when I follow step 4, the chart does not seem to load.  If I go to table tab and then come back to visualization tab, the graph can be seen. We want to the chart to be displayed as soon as we run a new query

**Comment by sharma2910** [comment]
@nbhavana 
i am not able to reproduce this, am i following the right step ? - 

https://github.com/siglens/siglens/assets/38106598/66ee22ba-04a1-464c-bdd6-ec6c76778b07

**Comment by nbhavana** [comment]
> @nbhavana i am not able to reproduce this, am i following the right steps ? -
> 
>  demo-1.mov

if you are already on visualization tab  and if you run the new query, the graph seems to load correctly. But if you follow these steps it does not work:
 1. Run the first query and stay on `table` tab.
 2. Now click `visualization` tab, you will see correct chart.
 3. Now run the second query while you are on `visualization` tab, the graph does not show up.

Can you try the above steps?

**Comment by sharma2910** [comment]
@nbhavana I tried the above steps, is this the expected outcome ? 

https://github.com/siglens/siglens/assets/38106598/09e29721-59bd-49ab-832f-0a0e1bc1849b

**Comment by nbhavana** [comment]
https://github.com/siglens/siglens/assets/6307537/6e45000f-012f-476a-8919-905556760ad5

**Comment by nbhavana** [comment]
> @nbhavana I tried the above steps, is this the expected outcome ?
> 
>  demo-4.mov




Uploading Screen Recording 2024-03-26 at 12.38.14 PM.mov…

**Comment by nbhavana** [comment]
> @nbhavana I tried the above steps, is this the expected outcome ?
> 
>  demo-4.mov

https://github.com/siglens/siglens/assets/6307537/4ee6d2cc-7a49-4f1c-9f88-308feffcb39f

**Comment by AndrewHess** [comment]
It looks like this issue is a bit flaky. So first someone might need to dig through the code and figure out a way to reliably reproduce the issue. After that, it will be much easier to test if the code changes fixed this issue

**Comment by sharma2910** [comment]
@AndrewHess @nbhavana 

Do you think adding more test data will help in reproducing this issue ?

**Comment by AndrewHess** [comment]
I doubt it, but maybe. My guess is that this is just a frontend issue; maybe we're rendering the new graphs behind the original graph sometimes, or something like that

**Pull request closed without merging**
