### PR TITLE
add tooltip on the bell icon

### PR DESCRIPTION
**Pull request by kashmii**
### actual requirements
* "to show a tooltip when users hover over the bell icon, saying 'Create alert in a new tab'"

https://github.com/siglens/siglens/issues/84 issue: Display a "open in a new tab" icon for add-to-dashboards/alerts. 

** This description has been changed, because the requirements have changed. **

### image

スクリーンショット 2023-11-26 11 21 49

This is my first time to contribute, so I apologize if I have done something wrong.

### CODE REVIEW

**Review by nkunal — COMMENTED** [review]
Changes are good, thanks for taking this up. We however need to give you a better icon image for the diagonal arrow, stay tuned.

**Comment by sonamgupta21** [comment]
Hi @kashmii,

There's a slight change in the issue.  Instead of adding "open in new tab" icon beside the bell icon, we now want to show a tooltip when users hover over the bell icon, saying '**Create alert in a new tab**' 

There is a merge conflict; if you believe you can resolve it, please do so and proceed with working on this pull request. However, if you encounter difficulties with conflict resolution, you can create a new pull request to address this issue.

For styling the tooltip, we would like it to be similar to the example shown below:
tooltip example

Thank you!

**Comment by kashmii** [comment]
Hi, @sonamgupta21
I've made the change and would appreciate a review.
Thank you in advance.

**Review by sonamgupta21 — CHANGES_REQUESTED** [review]
The tooltip is functioning correctly; however, when I click on the bell icon, the alert form opens in a new tab, but the tooltip does not hide in the previous tab. It should hide when the user clicks on the bell icon.

**Comment by kashmii** [comment]
Thank you for telling me that!
i fixed it, could you check this please?

---

https://github.com/siglens/siglens/assets/75294723/d19cf481-aa44-47f7-9e25-25f4de3505bf

**Comment by kashmii** [comment]
Hi, @sonamgupta21
Is there any problem about this?
if not,  I hope its merged. thanks.

**Comment by sonamgupta21** [comment]
Hey @kashmii, there is a slight change in this issue as the tooltip has some issues. (I have updated the issue)
Now, we want a popup so that the user can enter the alert name and then create an alert rule in a new tab.
 Let us know if you'd like to work on this issue. You can continue in this PR or close this one and create a new PR.

**Comment by kashmii** [comment]
Okay, understood. I will not do it this time.

**Pull request closed without merging**
