### PR TITLE
Allow dot in download names when saving files

### LINKED ISSUE #413: [UI] Allow Period (Dot) in Download Names
# Description 
Allow users to include periods in download names when saving files.
image

### PR DESCRIPTION
**Pull request by PratikshaPatil77**
# Description
Allowed users to include periods (dot) in download names when saving files.

Fixes #413 

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ x ] I have self-reviewed this PR.
- [ x ] I have removed all print-debugging and commented-out code that should not be merged.
- [ x ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by nbhavana — COMMENTED** [review]
This does not seem to fix the issue.image

**Comment by PratikshaPatil77** [comment]
> This does not seem to fix the issue.image

No it is working on my system

Uploading Screen Recording 2024-01-26 at 11.12.00 AM.mov…

**Comment by PratikshaPatil77** [comment]
> This does not seem to fix the issue.image


No it is working on my system
https://github.com/siglens/siglens/assets/128806421/c9b7bed7-2111-4338-8984-d1874093ab3d

Screen Recording 2024-01-26 at 11.12.00 AM

**Review by nbhavana — COMMENTED** [review]
1. The download on tracing page still does not seem to work.
image
2. On logs page,  it's letting user to add the dot in the name, but when you click download, it show an extra `.` in the file name which is not correct.
image

**Comment by AndrewHess** [comment]
This works for me. @nbhavana I had to run this in an incognito window, I think my normal chrome window was caching the JS file.

But there's a few things to fix. When I enter a filename and Save, it has two periods before the file extension.
Screenshot 2024-01-26 at 10 47 22
Screenshot 2024-01-26 at 10 47 32
Also, if we're saving as a CSV and include the .csv extension in the name we choose, the next screen should just have the .csv extension, not .csv.csv. (Same comment for JSON)
Screenshot 2024-01-26 at 10 46 08
Screenshot 2024-01-26 at 10 46 15

**Comment by PratikshaPatil77** [comment]
@nbhavana @AndrewHess @sonamgupta21 
Changes are ready for review. Can have a look and let me know if any changes required.
Screenshot 2024-01-29 at 11 20 20 AM
Screenshot 2024-01-29 at 11 31 48 AM

**Review by nbhavana — COMMENTED** [review]
The double dot is gone but when I don't give `.csv` or `.json` option 
image
then click save I see this 
image
On the download pop up window I don't see the .csv added to the file name. When i download, it save with correct extention. The user should see the `.csv` or `.json` added to the file name if not provided in the download pop up window

**Pull request merged**
