### PR TITLE
Fix: Allow the search block without using keyword "search"

### PR DESCRIPTION
**Pull request by Jiale-Fang**
# Description
In the past, only the first search block can execute without using keywrod `search`
E.g.:
`"Santa Ana" | search latency > 500000`

After this change, allow this type of query:
E.g.:
`"Santa Ana" | latency > 500000`

# Testing
Describe how you tested this code. How can the reviewers reproduce your tests?

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ ] I have self-reviewed this PR.
- [ ] I have removed all print-debugging and commented-out code that should not be merged.
- [ ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Comment by Jiale-Fang** [comment]
I believe the reason why we need to use keyword `search` for the following `search block` is because the rule for the `search block` is defined as follows:
`SearchBlock <- CMD_SEARCH clause:ClauseLevel4 {} `

There is a sub-rule in ClauseLevel4:
`UnnamedFieldWithStringValue <- value:String {} `

This means that if we do not use `CMD_SEARCH`, it will convert all other blocks as `SearchBlock` since all the blocks consist of strings.

Currently, if we want to support using `SearchBlock` without keyword `search`, I can only think of the following method:
`SearchBlock <- !(ALLCMD) CMD_SEARCH? clause:ClauseLevel4 {} `

Here, ALLCMD includes all commands we have:
```
ALLCMD <- (CMD_REGEX / CMD_STATS / ......) 

CMD_REGEX <- "regex" SPACE 
CMD_STATS <- "stats" SPACE 
......
```
Modifying `SearchBlock` to ensure it does not contain these existing commands should work. However, it seems somewhat arbitrary as a solution to this problem. What is your opinion on this?

**Comment by AndrewHess** [comment]
> Modifying `SearchBlock` to ensure it does not contain these existing commands should work. However, it seems somewhat arbitrary as a solution to this problem. What is your opinion on this?

I'm not thinking of a better way to do this either. This should work though

**Review by AndrewHess — COMMENTED** [review]
Looks good

**Review by AndrewHess — APPROVED** [review]

**Comment by AndrewHess** [comment]
@Jiale-Fang can you add some tests for this?

**Review by AndrewHess — APPROVED** [review]

**Pull request merged**
