### PR TITLE
Issue #415: Remove replace/append functionality

### LINKED ISSUE #415: [UI] Remove Replace/Append functionality from Logs Screen.
Remove the  point, click, search functionality from the Logs screen 
image

### PR DESCRIPTION
**Pull request by sanchitd9**
# Description
Removed the event handlers for selecting text.

Fixes #415  (link all the GitHub issues this addresses)

# Testing
Tested locally, the replace/append functionality doesn't show up now:

Screenshot from 2024-01-24 00-09-39

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by sonamgupta21 — APPROVED** [review]
Could you please remove references to the deleted JS file from all HTML files.

**Review by nbhavana — COMMENTED** [review]
this looks good. 
You should remove all the references of `point-click-search.js` file from the html files. Also, remove the reference from the css file.

**Comment by sanchitd9** [comment]
Removed all references to the deleted js file.

**Review by nbhavana — APPROVED** [review]
lgtm

**Pull request merged**
