### PR TITLE
Add validation and error handling to search endpoint

### LINKED ISSUE #577: [STORY] Ensure that the search endpoint contains all necessary properties and returns the correct status code.
# Description
- Validate the search endpoint `/api/search` and `/api/search/ws` to have the required properties before executing the search and return the appropriate status code for every request.
- The request JSON for the logs search looks like this 
```
{
  "state": "query",
  "searchText": "* | http_status=404",
  "startEpoch": "now-1h",
  "endEpoch": "now",
  "indexName": "*",
  "from": 0,
  "queryLanguage": "Splunk QL"
}
```
# Testing
- Test that no existing search functionality is broken and that validation is implemented for both `/api/search` and `/api/search/ws` endpoints.
- Manually test the endpoint with positive and negative testcases and verify that the appropriate status code is returned

### PR DESCRIPTION
**Pull request by ksankeerth**
# Description

- Added code to check unexpected fields in search endpoint's body
- If unexpected field exists in body, HTTP 400 will be returned to the user
- Added a test case 
- Fixed another minor bug in searchHandler

Fixes #577 

# Testing
- Added a test case 
- Tested manually 

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by AndrewHess — COMMENTED** [review]
This is looking great. A few things:
1. Just like for the `searchText` and `indexName` fields, for the other fields you should also log and return an error if we get to the `default` switch statement (and when the field is omitted, we should continue to give it the default value by going into the `if` block and skipping the `switch` inside the `else`)
2. Since the `ERROR_INVALID_FIELD_IN_BODY` and `ERROR_INVALID_VALUE_FOR_FIELD` are specific to the `ParseSearchBody` function, you can remove those definitions and just include the appropriate string in the error you create. That way we don't clutter the top of the file with error messages specific to each function we have

**Comment by ksankeerth** [comment]
Hi Team,
I've fixed code according to your suggestions. But E2E test fails. I'll check.

**Comment by AndrewHess** [comment]
> Hi Team, I've fixed code according to your suggestions. But E2E test fails. I'll check.

I think that failure was unreleated to your changes. I'll rerun the test and it might pass thisi time

**Comment by ksankeerth** [comment]
@AndrewHess  I'll add more test cases tonight.

**Review by AndrewHess — APPROVED** [review]
This looks great

**Pull request merged**
