### PR TITLE
Favorite Dashboard Functionality (Backend changes)

### LINKED ISSUE #151: Mark dashboards as favorites.(Backend)
# Description 
Implement backend functionality to support marking dashboards as favorites. 
Introduce a boolean attribute, such as isStarred, in the dashboard JSON to reflect the favorite status.

### PR DESCRIPTION
**Pull request by venkateshamatam**
# Description
This PR introduces the ability to mark dashboards as favorites. It adds a new boolean attribute `isFavorite` to the dashboard JSON, which reflects the favorite status. The favorite status can be toggled via a new API endpoint PUT `/dashboards/favorite/{dashboard-id}`

Fixes #151

# Testing
- Create a dashboard from the UI. The `isFavorite` property is initially set to false.
- Call the PUT `/dashboards/favorite/{dashboard-id}` endpoint with a valid dashboard ID and no request body. The response should return the updated `isFavorite` status.
- Verify the favorite status of the dashboard by inspecting the `isFavorite` attribute, which can be obtained by using the GET `dashboards/{dashboard-id}` API to fetch the dashboard details.
- Toggle the favorite status multiple times and ensure the `isFavorite` status is updated correctly each time.

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by nbhavana — COMMENTED** [review]
Thank you for submitting the PR. I was testing this PR and I observed that when you mark a dashboard as a favorite and then navigate to another page or refresh the current page, the dashboard is no longer marked as a favorite. Can you take a look the issue?

**Comment by venkateshamatam** [comment]
@nbhavana, Thank you for reviewing the PR. This code includes the backend changes, I see a seperate issue #152 to integrate the API into the UI. I tested this using postman and curl by hitting the endpoints manually and seeing the API response.

**Review by nbhavana — DISMISSED** [review]
lgtm

**Comment by nbhavana** [comment]
@venkateshamatam the units tests are failing for this PR. To take look at it you can click on the details of `siglens-lint-ut/golang-cicd(pull_request)` 
image

image

**Comment by venkateshamatam** [comment]
Hello @nbhavana, it looks like there was a merge conflict in server.go and I resolved the conflict. The tests related to dashboards I believe are storing the IDs from the previous tests and when you run the subsequent test again it fails because there already exists a dashboard from the previous run. Now the tests ran again after fixing a conflict and they passed this time.

**Pull request merged**
