### PR TITLE
Feat: Added Download Formats Options (XML/SQL)

### PR DESCRIPTION
**Pull request by miguelteixeira123456789**
# Description
Added two new options (XML and SQL) for data download. These work similarly to what we already have for the formats CSV and JSON.
Also added two new tests, one for each new type of download format. These run a basic test confirming that, when we download the data, it is indeed in the format intended and with all the information needed.

Co-authored-by: Rodrigo Alves [rodrigo.lucas.alves@tecnico.ulisboa.pt]

# Testing
1. If you don't already have data loaded, go to Ingestion and Send Test Data.
2. Go to Logs, and click the download button.
3. Click Download as XML or Download as SQL.
4. This should download a file to your local computer, with the data in the format selected.

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by sonamgupta21 — CHANGES_REQUESTED** [review]
When downloading logs in XML and SQL formats from the log screen, the files appear correctly formatted. However, on the search traces screen, the XML and SQL formats are not displayed correctly.

**Comment by miguelteixeira123456789** [comment]
> When downloading logs in XML and SQL formats from the log screen, the files appear correctly formatted. However, on the search traces screen, the XML and SQL formats are not displayed correctly.

We've changed the format. Could you please check if everything is correct?

**Review by sonamgupta21 — APPROVED** [review]
Looks Good!

**Comment by sonamgupta21** [comment]
@miguelteixeira123456789  Please update your branch.

**Comment by miguelteixeira123456789** [comment]
> @miguelteixeira123456789 Please update your branch.

@sonamgupta21 Done.

**Pull request merged**
