### PR TITLE
Fixed Tooltip/Legends for Metrics Formula Graphs

### PR DESCRIPTION
**Pull request by Divyanshu11011**
# Description
Fix Tooltip/Legends for Metrics Formula Graphs for complex formulae's 

# Snapshot
image

### CODE REVIEW

**Review by sonamgupta21 — COMMENTED** [review]
image

It should show the timestamp and query like this.

**Comment by Divyanshu11011** [comment]
image
Fixed that @sonamgupta21 kindly review

**Comment by sonamgupta21** [comment]
@Divyanshu11011 Make sure the formula tooltip works fine on every page alerts and dashboards. On Alerts I see the error 
image
and on dashboards it is not coming correctly.
image

**Comment by Divyanshu11011** [comment]
Dashboard:-
image

Alert:-
image

Metrix ex:-
image

**Review by sonamgupta21 — APPROVED** [review]
Everything looks good to me. 
One thing, on dashboard screen it still shows formula as `a` `a+100`.
image
This can be fixed in another PR.

**Pull request merged**
