### PR TITLE
Fix: Spl rex block

### PR DESCRIPTION
**Pull request by Jiale-Fang**
# Description
Fix bug for rex block without group by cols.

# Testing
Describe how you tested this code. How can the reviewers reproduce your tests?

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ ] I have self-reviewed this PR.
- [ ] I have removed all print-debugging and commented-out code that should not be merged.
- [ ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Review by AndrewHess — COMMENTED** [review]
When I run:
```
city=Boston | rex field=weekday "(?<first>[A-Z].{2})(?<second>.*)"
```
it works correctly, but when I run:
```
city=Boston | rex field=weekday "(?<first>[A-T].{2})(?<second>.*)"
```
I get a bunch of these errors and I don't see the new `first` and `second` fields
```
ERRO[2024-01-03 14:54:27] PostQueryBucketCleaning: performAggOnResult: performLetColumnsRequest: performRexColRequest: performRexColRequestWithoutGroupby: MatchAndExtractGroups: no str in field match the pattern
```

**Comment by Jiale-Fang** [comment]
I think the reason is because `Wednesday` not start with [A-T], so for record which weekday is `Wednesday`. It can not find a match for that.

**Comment by AndrewHess** [comment]
> I think the reason is because `Wednesday` not start with [A-T], so for record which weekday is `Wednesday`. It can not find a match for that.

Right, but shouldn't it still give some data? Either just the rows that were successfully extracted or all the rows with nil values for the extracted fields for rows like Wednesday? Or maybe I'm misremembering how rex is supposed to work

**Comment by Jiale-Fang** [comment]
image

**Comment by Jiale-Fang** [comment]
> > I think the reason is because `Wednesday` not start with [A-T], so for record which weekday is `Wednesday`. It can not find a match for that.
> 
> Right, but shouldn't it still give some data? Either just the rows that were successfully extracted or all the rows with nil values for the extracted fields for rows like Wednesday? Or maybe I'm misremembering how rex is supposed to work

Can you take a look of the pic above. It is the screenshot of Splunk

**Review by AndrewHess — APPROVED** [review]
Looks good

**Pull request merged**
