### PR TITLE
feat: Update dashboard panels layout and positioning

### LINKED ISSUE #922: UI - Update Default Dashboard Dimensions According to New Library
# Description
Update the default dashboards dimensions to utilize Gridstack's grid system. Previously, the positions (x, y) and sizes (width, height) were defined in pixels. These need to be converted to Gridstack's grid units to ensure proper integration and functionality with the new library.

# Benefits
Describe why you want this feature.

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Add anything else we should know about this.

### PR DESCRIPTION
**Pull request by navyayy**
# Description
The height `h` and width `w` of the JSON files of dashboards have been changed, to accommodate the new height and width standards, which was previously pixels.

Fixes #922 

# Testing
The following dashboards are verified:
image
image
image

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Comment by sunitakawane** [comment]
@navyayy can you adjust the x,y params such that there are only 2 panels in one row.  You can increase width by 1 .

**Comment by navyayy** [comment]
> @navyayy can you adjust the x,y params such that there are only 2 panels in one row. You can increase width by 1 .

@sunitakawane Okay, I will update it.

**Comment by navyayy** [comment]
> @navyayy can you adjust the x,y params such that there are only 2 panels in one row. You can increase width by 1 .

@sunitakawane I have updated the panels and also the screenshots in the description.

**Review by sonamgupta21 — APPROVED** [review]
Looks good.

**Pull request merged**
